apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aq17azw13-python 
  janus-idp.io/tekton: aq17azw13-python
  backstage.io/kubernetes-id: aq17azw13-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aq17azw13-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml